apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: inventory-db
  namespace: inventory
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: inventory
      owner: inventory
