apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - target:
      kind: Cluster
      name: catalog-db
    patch: |
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: catalog-db
      spec:
        instances: 3
